version: "3.7"
services:
  database:
    container_name: pg
    image: postgres:latest
    environment:
      POSTGRES_DB: go-mux-db
    volumes:
      - ./resources/migrations/001__schema.up.sql
    ports:
      - "5432:5432"